[profile.default]
failure-output = "immediate-final"
fail-fast      = false

[profile.ci]
retries        = 1
failure-output = "immediate-final"
slow-timeout   = { period = "30s", terminate-after = 4 }
